# Generated by Django 4.1.2 on 2022-10-24 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("location", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("completed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("c", "Created"), ("p", "In Progress"), ("f", "Failed"), ("d", "Done")],
                        default="c",
                        max_length=1,
                    ),
                ),
                ("screen_width", models.PositiveSmallIntegerField()),
                ("screen_height", models.PositiveSmallIntegerField()),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("Desktop", "Desktop"),
                            ("Mobile", "Mobile"),
                            ("Tablet", "Tablet"),
                            ("Random", "Random"),
                        ],
                        default="Random",
                        max_length=20,
                    ),
                ),
                (
                    "screen_size",
                    models.CharField(
                        choices=[("Big", "Big"), ("Medium", "Medium"), ("Small", "Small"), ("Random", "Random")],
                        default="Random",
                        max_length=20,
                    ),
                ),
                ("periodic", models.BooleanField(default=False)),
                ("repeat", models.PositiveSmallIntegerField(default=1)),
                ("repeat_every_min_start", models.PositiveSmallIntegerField()),
                ("repeat_every_min_end", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("visit_x_nuber_of_first_results", models.PositiveSmallIntegerField(blank=True, default=4)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("start_time", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="location.city"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="location.country"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="visits", to="job.task"
                    ),
                ),
            ],
        ),
    ]
